### PR TITLE
Introduce option to inherit combined sampler bindings

### PR DESCRIPTION
**Pull request by amzeratul**
This pull request introduces a new option that enables inheriting of combined sampler bindings.

For an example, consider the original HLSL fragment:

```
Texture2D tex0 : register(t0);
Texture2D tex1 : register(t1);
Texture2D tex2 : register(t2);
Texture2D tex3 : register(t3);
SamplerState sampler0 : register(s0);
SamplerState sampler1 : register(s1);
SamplerState sampler2 : register(s2);
SamplerState sampler3 : register(s3);
```

And the output with the option disabled (default/old behaviour):

```
uniform sampler2D SPIRV_Cross_Combinedtex0sampler0;
uniform sampler2D SPIRV_Cross_Combinedtex2sampler2;
uniform sampler2D SPIRV_Cross_Combinedtex3sampler3;
uniform sampler2D SPIRV_Cross_Combinedtex1sampler1;
```

And compare with the output with the same option enabled:

```
layout(binding = 0) uniform sampler2D SPIRV_Cross_Combinedtex0sampler0;
layout(binding = 2) uniform sampler2D SPIRV_Cross_Combinedtex2sampler2;
layout(binding = 3) uniform sampler2D SPIRV_Cross_Combinedtex3sampler3;
layout(binding = 1) uniform sampler2D SPIRV_Cross_Combinedtex1sampler1;
```

Note that in this particular (real world) example, the bindings changed. This is because SPIRV-Cross generates the combined samplers in the order of post-optimization usage, and not order of original binding or declaration.

Without this option, it's impossible to write a generic system that will bind the GLSL textures to the same bindings as the original HLSL.

This patch merely invokes the util method already provided by SPIRV-Cross.

### CODE REVIEW

**Comment by amzeratul** [comment]
Sorry that it took me so long to get the CLA signed!

**Comment by amzeratul** [comment]
Sorry to tag you @gongminmin , but is there any feedback that I could get on this Pull Request? It'd be quite helpful for me if this could get merged into the repo!

**Comment by gongminmin** [comment]
@amzeratul Sorry I have left the company and no longer officially work on this project. Your change looks good to me. But I don't think I can merge it. @pow2clk , could you take over? Thanks.

**Comment by pow2clk** [comment]
Hi @amzeratul!

I'm a fan of Chucklefish and I'd like to help out. I'm a bit unfamiliar with the ins and outs of spirv cross and shaderconductor at the moment, but I trust @gongminmin's judgement.

Nevertheless, I'd like to tag @ehsannas in case he has any alternative suggestions that might be useful.

**Comment by amzeratul** [comment]
Thank you all! :D

**Review by KFCMULLBANK — APPROVED** [review]

**Pull request merged**
