### PR TITLE
Disassemble option

### PR DESCRIPTION
**Pull request by Jorgemagic**
Hi Minmin Gong,

  I added a new **Disassemble option** in TargetDesc to get disassemble Spirv for debug purposes. I hope that you find it useful to merge. Next step should be disassemble DXIL too.

_Note.  I linked spirv-tools for this feature._

Regards,
Jorge

### CODE REVIEW

**Comment by Jorgemagic** [comment]
**SpirVAsm** and **DxilAsm** was my first idea, but I thought that these are really not different shading languages, In other hands _version_ option is not used in all case, so I think that we can add a new disassemble option only for binary shading languages.

Another option will be create an addition method to disassemble the ResultDesc from Compile method.

In addition there are some more options that can be neccessary add to _TargetDesc_ in the future and only will be useful with some languages, For example **DXC** options to convert to **Spirv**:

-**Zpc**: _Packs matrices in column-major order by deafult_
-**Zpr**: _Packs matrices in row-major order by deafult_

In this [link ](https://antiagainst.github.io/post/hlsl-for-vulkan-matrices/) you can find an interesting article about convert HLSL to SpirV Matrices and -Zpc/-Zpr options are very important.

Where do you think that we can add this options?

**Comment by Jorgemagic** [comment]
Ok, tomorrow I will add new disassemble method in Shader conductor interface and C# wrapper.

I like idea to add one or more fields to SourceDesc for DXC compile options. 

Maybe the most flexible and easiest implementation would be to add a extra string option and add this plain string to DXC compile params together -spirv param. The downside is that should be used with caution.

**Comment by Jorgemagic** [comment]
Hi Minmin Gong,

I created a new **Disassemble** method on ShaderConductor interface and I updated C# wrapper with this new feature.  What do you think?

**Comment by gongminmin** [comment]
It looks good. Thanks very much. I'll merge it when CI passes.

**Pull request merged**
